'use client'
import {useEffect,useState} from 'react'
import {supabase} from '../lib/supabase'
const areas=['Audiologia','Voz','Fala','Linguagem','Fluência','Motricidade Orofacial','Deglutição','Aprendizagem','Desenvolvimento Infantil','Comunicação Social']
export default function Home(){
const [session,setSession]=useState(null),[loading,setLoading]=useState(true),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[patients,setPatients]=useState([]),[profile,setProfile]=useState(null),[selected,setSelected]=useState(null),[tab,setTab]=useState('dashboard')
const [form,setForm]=useState({full_name:'',birth_date:'',phone:'',responsible:'',occupation_school:'',notes:''})
const [assessment,setAssessment]=useState({area:'Audiologia',chief_complaint:'',history:''})
const [evolution,setEvolution]=useState({activities:'',response:'',next_conduct:''})
useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)loadUser(data.session.user.id);else setLoading(false)});const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(s)loadUser(s.user.id);else setLoading(false)});return()=>l.subscription.unsubscribe()},[])
async function loadUser(uid){const {data:p}=await supabase.from('profiles').select('*, clinics(name)').eq('id',uid).single();setProfile(p);if(p?.clinic_id){const {data:ps}=await supabase.from('patients').select('*').eq('clinic_id',p.clinic_id).order('created_at',{ascending:false});setPatients(ps||[])}setLoading(false)}
async function login(e){e.preventDefault();setError('');const {error:e2}=await supabase.auth.signInWithPassword({email,password});if(e2)setError(e2.message)}
async function logout(){await supabase.auth.signOut();setSelected(null);setTab('dashboard')}
async function savePatient(e){e.preventDefault();setError('');if(!profile?.clinic_id)return setError('Usuário sem clínica vinculada.');const {data,error:e2}=await supabase.from('patients').insert({...form,clinic_id:profile.clinic_id,created_by:session.user.id}).select().single();if(e2)return setError(e2.message);setPatients([data,...patients]);setForm({full_name:'',birth_date:'',phone:'',responsible:'',occupation_school:'',notes:''});setSelected(data);setTab('patient')}
async function saveAssessment(e){e.preventDefault();if(!selected)return;const {error:e2}=await supabase.from('assessments').insert({clinic_id:profile.clinic_id,patient_id:selected.id,professional_id:session.user.id,area:assessment.area,chief_complaint:assessment.chief_complaint,history:assessment.history});if(e2)return setError(e2.message);setAssessment({area:'Audiologia',chief_complaint:'',history:''});alert('Anamnese salva.')}
async function saveEvolution(e){e.preventDefault();if(!selected)return;const {data:old}=await supabase.from('evolutions').select('session_number').eq('patient_id',selected.id).order('session_number',{ascending:false}).limit(1);const n=(old?.[0]?.session_number||0)+1;const {error:e2}=await supabase.from('evolutions').insert({clinic_id:profile.clinic_id,patient_id:selected.id,professional_id:session.user.id,session_number:n,...evolution});if(e2)return setError(e2.message);setEvolution({activities:'',response:'',next_conduct:''});alert('Evolução salva.')}
if(loading)return <main className="center">Carregando FonoClinic…</main>
if(!session)return <main className="login"><div className="loginCard"><div className="logo">F</div><h1>FonoClinic</h1><p>Sistema clínico de Fonoaudiologia</p><form onSubmit={login}><label>E-mail<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label><label>Senha<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required/></label>{error&&<div className="error">{error}</div>}<button>Entrar</button></form></div></main>
return <main className="app"><header><div><b>FonoClinic</b><span> • {profile?.clinics?.name||'Clínica'}</span></div><div className="user">{profile?.full_name||session.user.email}<button onClick={logout}>Sair</button></div></header><nav><button className={tab==='dashboard'?'active':''} onClick={()=>setTab('dashboard')}>Painel</button><button className={tab==='new'?'active':''} onClick={()=>setTab('new')}>+ Paciente</button><button className={tab==='patient'?'active':''} disabled={!selected} onClick={()=>setTab('patient')}>Prontuário</button></nav>{error&&<div className="globalError">{error}</div>}
{tab==='dashboard'&&<section className="content"><h2>Painel clínico</h2><div className="cards"><div><strong>{patients.length}</strong><small>Pacientes</small></div><div><strong>FonoClinic</strong><small>Ambiente clínico</small></div><div><strong>{profile?.role||'-'}</strong><small>Perfil</small></div></div><div className="panel"><h3>Pacientes recentes</h3>{patients.length===0?<p>Nenhum paciente cadastrado.</p>:<div className="list">{patients.map(p=><button key={p.id} onClick={()=>{setSelected(p);setTab('patient')}}><b>{p.full_name}</b><span>{p.phone||'Sem telefone'}</span></button>)}</div>}</div></section>}
{tab==='new'&&<section className="content"><h2>Novo paciente</h2><form className="panel form" onSubmit={savePatient}><label>Nome completo*<input required value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label><div className="grid"><label>Data de nascimento<input type="date" value={form.birth_date} onChange={e=>setForm({...form,birth_date:e.target.value})}/></label><label>Telefone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label></div><label>Responsável<input value={form.responsible} onChange={e=>setForm({...form,responsible:e.target.value})}/></label><label>Profissão / escola<input value={form.occupation_school} onChange={e=>setForm({...form,occupation_school:e.target.value})}/></label><label>Observações<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button>Salvar paciente</button></form></section>}
{tab==='patient'&&selected&&<section className="content"><div className="patientHead"><div><h2>{selected.full_name}</h2><p>{selected.birth_date||'Data não informada'} • {selected.phone||'Sem telefone'}</p></div><button onClick={()=>setTab('dashboard')}>Voltar</button></div><div className="panel"><h3>Anamnese / avaliação</h3><form className="form" onSubmit={saveAssessment}><label>Área<select value={assessment.area} onChange={e=>setAssessment({...assessment,area:e.target.value})}>{areas.map(a=><option key={a}>{a}</option>)}</select></label><label>Queixa principal<textarea value={assessment.chief_complaint} onChange={e=>setAssessment({...assessment,chief_complaint:e.target.value})}/></label><label>História / informações relevantes<textarea value={assessment.history} onChange={e=>setAssessment({...assessment,history:e.target.value})}/></label><button>Salvar avaliação</button></form></div><div className="panel"><h3>Evolução</h3><form className="form" onSubmit={saveEvolution}><label>Atividades realizadas<textarea value={evolution.activities} onChange={e=>setEvolution({...evolution,activities:e.target.value})}/></label><label>Resposta do paciente<textarea value={evolution.response} onChange={e=>setEvolution({...evolution,response:e.target.value})}/></label><label>Próxima conduta<textarea value={evolution.next_conduct} onChange={e=>setEvolution({...evolution,next_conduct:e.target.value})}/></label><button>Registrar evolução</button></form></div></section>}</main>
}